In [175]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import make_classification
import warnings
warnings.filterwarnings("ignore")


In [176]:
x,y=make_classification(n_samples=1000,
    n_features=10,
    n_classes=2,
    random_state=1)

In [177]:
pd.DataFrame(x)

,0,1,2,3,4,5,6,7,8,9
0,-2.101187,-0.247208,-1.989335,-1.484556,1.128668,-0.925564,1.210290,2.070526,0.091527,-2.376400
1,0.323703,-0.126894,-1.309524,-0.022738,-0.398725,0.280419,0.034598,1.184820,-0.186802,1.969326
2,2.232038,0.334123,-0.852703,3.289016,0.331944,0.044767,-2.233844,-0.066448,-0.313881,1.499174
3,-0.428456,1.627132,0.484649,0.938373,1.339947,-0.869036,0.943132,0.713558,-0.468041,0.075341
4,0.386012,0.338141,-0.186530,2.369137,1.667284,-0.979107,0.951526,0.398790,0.729005,0.372213
...,...,...,...,...,...,...,...,...,...,...
995,-1.148812,-0.048464,0.555170,-2.167311,-0.595136,0.237045,-1.241394,-0.144619,-0.136638,-1.363868
996,1.585814,1.269868,1.193456,2.321360,0.222056,0.040255,2.260748,-0.182916,-0.959332,0.263967
997,-1.169663,0.230641,-2.710394,-3.217224,-1.509607,0.795293,-0.854581,0.021500,-1.066801,0.528868
998,-2.646182,-0.117844,0.149377,-0.377960,2.755272,-1.983281,-1.865016,0.340473,-0.276940,-0.871014


In [178]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=1)

In [179]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [180]:
model.fit(xtrain,ytrain)

LogisticRegression()

In [181]:
ypred=model.predict(xtest)
ypred

array([0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0])

In [182]:
model.predict_proba(xtest) #will give the prbabilty in both category when a new datapoint came.

array([[8.52210918e-01, 1.47789082e-01],
       [9.26249026e-01, 7.37509738e-02],
       [1.41621086e-01, 8.58378914e-01],
       [9.97714456e-01, 2.28554365e-03],
       [2.52447120e-01, 7.47552880e-01],
       [9.55608059e-02, 9.04439194e-01],
       [1.69748901e-02, 9.83025110e-01],
       [9.79676314e-01, 2.03236862e-02],
       [4.27887381e-01, 5.72112619e-01],
       [6.39943524e-01, 3.60056476e-01],
       [9.81841331e-01, 1.81586686e-02],
       [9.95584623e-01, 4.41537703e-03],
       [8.66681238e-01, 1.33318762e-01],
       [5.44354071e-02, 9.45564593e-01],
       [4.35856786e-02, 9.56414321e-01],
       [6.96974144e-01, 3.03025856e-01],
       [1.11460546e-01, 8.88539454e-01],
       [2.51791689e-01, 7.48208311e-01],
       [7.22127931e-03, 9.92778721e-01],
       [2.60680356e-02, 9.73931964e-01],
       [9.55301699e-01, 4.46983010e-02],
       [6.94712664e-01, 3.05287336e-01],
       [1.84689847e-01, 8.15310153e-01],
       [6.65542385e-02, 9.33445762e-01],
       [9.395308

In [183]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [184]:
score=accuracy_score(ypred,ytest)

In [185]:
score

0.88

In [186]:
score=confusion_matrix(ypred,ytest)

In [187]:
score

array([[139,  16],
       [ 20, 125]])

In [188]:
score=classification_report(ypred,ytest)

In [189]:
score

'              precision    recall  f1-score   support\n\n           0       0.87      0.90      0.89       155\n           1       0.89      0.86      0.87       145\n\n    accuracy                           0.88       300\n   macro avg       0.88      0.88      0.88       300\nweighted avg       0.88      0.88      0.88       300\n'

## Hyperparameter tuning

In [190]:
penalty=["l1","l2","elasticnet"]
c=[100,10,1.0,0.1,0.01]
solver=["sag","saga","liblinear","lbfgs","newton-cg"]
params=dict(penalty=penalty,C=c,solver=solver)

In [191]:
#grid search cv
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()
grid=GridSearchCV(estimator=model,param_grid=params,scoring="accuracy",cv=5,n_jobs=-1)#njobs uses all the processors in the system

In [192]:
grid

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['sag', 'saga', 'liblinear', 'lbfgs',
                                    'newton-cg']},
             scoring='accuracy')

In [193]:
grid.fit(xtrain,ytrain)


/Users/sharafunneesapp/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/sharafunneesapp/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/sharafunneesapp/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/sharafunneesapp/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/sharafunneesapp/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/sharafun

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['sag', 'saga', 'liblinear', 'lbfgs',
                                    'newton-cg']},
             scoring='accuracy')

In [194]:
grid.best_params_

{'C': 0.01, 'penalty': 'l1', 'solver': 'saga'}

In [195]:
grid.best_score_

0.8471428571428572

In [196]:
grid.predict(xtest)

array([0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0])

In [197]:
score=accuracy_score(ypred,ytest)

In [198]:
score

0.88

In [199]:
from sklearn.model_selection import RandomizedSearchCV
random=RandomizedSearchCV(estimator=model,param_distributions=params,scoring="accuracy",cv=5,n_jobs=-1)


In [200]:
random

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['sag', 'saga', 'liblinear',
                                                   'lbfgs', 'newton-cg']},
                   scoring='accuracy')

In [201]:
random.fit(xtrain,ytrain)

/Users/sharafunneesapp/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/sharafunneesapp/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/sharafunneesapp/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/sharafunneesapp/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/sharafunneesapp/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['sag', 'saga', 'liblinear',
                                                   'lbfgs', 'newton-cg']},
                   scoring='accuracy')

In [202]:
random.predict(xtest)

array([0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0])

In [203]:
random.best_params_

{'solver': 'lbfgs', 'penalty': 'l2', 'C': 0.01}

In [204]:
score=accuracy_score(ypred,ytest)

In [205]:
score

0.88